spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  datasource:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.springframework.test.context.cache: TRACE

